/* Owner reports are generated on demand; documents are never uploaded. */
let orderPageRows=[],orderPageMore=false,orderPageCursor=null,orderPageRequest=0,orderSearchTimer=null;
let reportGeneration=0,reportCache=new Map(),reportInflight=new Map(),salesReportData=null,customerOffset=0;
function reportOwner(){return adminAccessAllowed&&adminRole==='owner';}
function reportError(id){document.getElementById(id).innerHTML='<div class="message error">No se pudo cargar el resumen completo. Pulsa Actualizar para volver a intentar. No se muestran totales parciales.</div>';}
let reportAsOf=Date.now();
function reportBounds(days){return {from:days==='all'?null:new Date(reportAsOf-Number(days)*86400000).toISOString(),to:new Date(reportAsOf).toISOString()};}
async function getSalesSummary(bounds,customers=false,offset=0){
 if(!reportOwner())throw new Error('NO_AUTORIZADO');
 const user=adminSession?.user?.id,generation=reportGeneration,key=JSON.stringify([user,bounds.from,bounds.to,customers,offset]);
 if(reportCache.has(key))return reportCache.get(key);if(reportInflight.has(key))return reportInflight.get(key);
 const promise=(async()=>{const {data,error}=await db.rpc('pastehot_sales_summary',{p_from:bounds.from,p_to:bounds.to,p_customers:customers,p_customer_offset:offset});if(error||!data)throw error||new Error('Resumen no disponible');if(!reportOwner()||user!==adminSession?.user?.id||generation!==reportGeneration)throw new Error('SESION_CAMBIO');reportCache.set(key,data);return data;})();
 reportInflight.set(key,promise);try{return await promise}finally{reportInflight.delete(key);}
}
function invalidateSalesReports(){reportAsOf=Date.now();salesReportRequest++;reportGeneration++;reportCache.clear();salesReportData=null;document.querySelectorAll('[data-report-export]').forEach(b=>b.disabled=true);}
function resetAdminReports(){resetImageMaintenance();invalidateSalesReports();orderPageRequest++;orderPageRows=[];orderPageCursor=null;clearTimeout(orderSearchTimer);document.getElementById('ordersTable').textContent='';document.getElementById('salesReportContent').textContent='';['ordersMetrics','productSalesChart','dailySalesChart','pasteSalesMetrics','pasteSalesTable','customersMetrics','customersTable'].forEach(id=>document.getElementById(id).textContent='');}
function mergeOrderCache(rows){const map=new Map(orders.map(o=>[String(o.id),o]));rows.forEach(o=>map.set(String(o.id),o));orders=[...map.values()].sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at)||String(b.id).localeCompare(String(a.id)));}
async function loadOrderPage(append=false){
 if(!adminAccessAllowed)return;const request=++orderPageRequest,user=adminSession?.user?.id,role=adminRole,search=document.getElementById('orderSearch').value.trim();
 if(!append){orderPageRows=[];orderPageCursor=null;renderOrderPage();}document.getElementById('ordersSearchCount').textContent='Buscando pedidos…';
 const from=role==='owner'?(search?null:reportBounds(ordersPeriod.value).from):new Date(Date.now()-48*3600000).toISOString();
 const cursor=append?orderPageCursor:null;
 const {data,error}=await db.rpc('pastehot_order_page',{p_from:from,p_search:search,p_before_time:cursor?.created_at||null,p_before_id:cursor?.id||null});
 if(request!==orderPageRequest||!adminAccessAllowed||adminSession?.user?.id!==user||role!==adminRole)return;
 if(error||!data){document.getElementById('ordersSearchCount').textContent='La consulta optimizada está pendiente de activación o no pudo completarse. Vuelve a intentar con Actualizar.';return;}
 orderPageRows=append?[...new Map([...orderPageRows,...data.rows].map(o=>[String(o.id),o])).values()]:data.rows;orderPageMore=data.has_more;orderPageCursor=orderPageRows.at(-1)||null;mergeOrderCache(data.rows);renderOrderPage();
}
function renderOrderPage(){
 const keep=orders,period=ordersPeriod.value;orders=orderPageRows;ordersPeriod.value='all';try{window.pastehotLegacyOrderTable();}finally{orders=keep;ordersPeriod.value=period;}
 document.getElementById('ordersSearchCount').textContent=`${orderPageRows.length} pedido${orderPageRows.length===1?'':'s'} cargado${orderPageRows.length===1?'':'s'}${orderPageMore?' · Hay más resultados':''}`;
 document.getElementById('ordersMore').classList.toggle('hidden',!orderPageMore);
}
function searchOrdersRemote(){clearTimeout(orderSearchTimer);orderSearchTimer=setTimeout(()=>loadOrderPage(false),300);}
async function loadOrdersOptimized(){
 if(ordersLoadingPromise){ordersReloadRequested=true;return ordersLoadingPromise;}
 const user=adminSession?.user?.id,role=adminRole;
 ordersLoadingPromise=(async()=>{try{do{ordersReloadRequested=false;const recent=[];
 for(let offset=0;;offset+=1000){const {data,error}=await db.from('orders').select('*').gte('created_at',new Date(Date.now()-48*3600000).toISOString()).order('created_at',{ascending:false}).order('id',{ascending:false}).range(offset,offset+999);if(error)throw error;recent.push(...data);if(data.length<1000)break;}
 if(!adminAccessAllowed||adminSession?.user?.id!==user||role!==adminRole)return;
 // Reconcile only the recent window, retaining archived details only while in use.
 orders=recent;mergeOrderCache(orderPageRows);reconcileOrderInbox(recent);invalidateSalesReports();
 await loadOrderPage(false);document.getElementById('ordersLoadMessage').textContent='';
 if(reportOwner()){if(document.getElementById('section-orders').classList.contains('active'))await renderOrderAnalytics();if(document.getElementById('section-customers').classList.contains('active'))await renderCustomers();if(document.getElementById('section-paste-sales').classList.contains('active'))await renderPasteSales();}
 }while(ordersReloadRequested);}catch{showMessage('ordersLoadMessage','No se pudo actualizar. Los datos anteriores pueden estar desactualizados; pulsa Actualizar.',false);invalidateSalesReports();}})();
 try{await ordersLoadingPromise}finally{ordersLoadingPromise=null;}
}
function handleOrderRealtimeChange(payload){
 if(!adminAccessAllowed)return;
 if(payload.eventType==='DELETE'){orders=orders.filter(o=>String(o.id)!==String(payload.old?.id));orderPageRows=orderPageRows.filter(o=>String(o.id)!==String(payload.old?.id));}
 else if(payload.new?.id)mergeOrderCache([payload.new]);
 invalidateSalesReports();reconcileOrderInbox(orders.filter(o=>Date.parse(o.created_at)>=Date.now()-48*3600000));
 clearTimeout(adminOrdersTimer);adminOrdersTimer=setTimeout(async()=>{if(!adminAccessAllowed)return;if(document.getElementById('section-orders').classList.contains('active')){await loadOrderPage(false);if(reportOwner())await renderOrderAnalytics();}else if(reportOwner()&&document.getElementById('section-customers').classList.contains('active'))await renderCustomers();else if(reportOwner()&&document.getElementById('section-paste-sales').classList.contains('active'))await renderPasteSales();},180);
}
async function renderServerAnalytics(){if(!reportOwner())return;const period=ordersPeriod.value,generation=reportGeneration;try{const d=await getSalesSummary(reportBounds(period));if(period!==ordersPeriod.value||generation!==reportGeneration)return;const best=[...d.daily].sort((a,b)=>b.amount-a.amount)[0];ordersMetrics.innerHTML=metric('Pedidos',d.orders)+metric('Ventas',formatMoney(d.total))+metric('Ticket promedio',formatMoney(d.orders?d.total/d.orders:0))+metric('Mejor día',best?`${best.day} · ${formatMoney(best.amount)}`:'—');renderBarChart(productSalesChart,d.pastes.slice(0,8).map(p=>[p.name,p.quantity]),v=>`${v} u.`);renderBarChart(dailySalesChart,d.daily.slice(-14).map(d=>[d.day,d.amount]),formatMoney);}catch{reportError('ordersMetrics');}}
async function renderServerPasteSales(){if(!reportOwner())return;const period=pasteSalesPeriod.value,generation=reportGeneration;try{const d=await getSalesSummary(reportBounds(period));if(period!==pasteSalesPeriod.value||generation!==reportGeneration)return;const total=d.pastes.reduce((a,p)=>a+Number(p.quantity),0),best=d.pastes.find(p=>p.quantity>0);pasteSalesMetrics.innerHTML=metric('Pastes vendidos',total)+metric('Más vendido',best?.name||'Sin ventas')+metric('Unidades del más vendido',best?.quantity||0);pasteSalesTable.innerHTML=d.pastes.map((p,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(p.name)}</td><td><strong>${p.quantity}</strong></td></tr>`).join('')||'<tr><td colspan="3">Sin pastes registrados.</td></tr>';}catch{reportError('pasteSalesMetrics');pasteSalesTable.textContent='';}}
async function renderServerCustomers(append=false){if(!reportOwner())return;if(!append)customerOffset=0;const period=customersPeriod.value,generation=reportGeneration;try{const d=await getSalesSummary(reportBounds(period),true,customerOffset);if(period!==customersPeriod.value||generation!==reportGeneration)return;customersMetrics.innerHTML=metric('Clientes del periodo',d.customer_count)+metric('Nuevos',d.customer_count-d.recurrent_count)+metric('Recurrentes',d.recurrent_count)+metric('Venta del periodo',formatMoney(d.customer_total));const rows=d.customers.slice(0,50).map(c=>`<tr><td>${escapeHtml(c.name)}</td><td>${escapeHtml(c.phone)}</td><td>${c.count}</td><td>${formatMoney(c.total)}</td><td>${dateOnly(c.first)}</td><td>${dateOnly(c.last)}</td><td>${c.recurrent?'Recurrente':'Nuevo'}</td></tr>`).join('');if(append)customersTable.insertAdjacentHTML('beforeend',rows);else customersTable.innerHTML=rows||'<tr><td colspan="7">Sin compras en el periodo.</td></tr>';document.getElementById('customersMore').classList.toggle('hidden',d.customers.length<=50);customerOffset+=50;}catch{reportError('customersMetrics');}}
function localReportDay(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Merida',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function calendarReportBounds(type,day){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(day))throw new Error('Selecciona una fecha válida.');
 const ref=new Date(day+'T00:00:00-06:00');if(!Number.isFinite(ref.getTime()))throw new Error('Selecciona una fecha válida.');
 if(type==='all')return {from:null,to:new Date().toISOString(),label:'Todo el historial'};
 let from,to;if(type==='week'){const weekday=new Date(day+'T12:00:00Z').getUTCDay(),diff=(weekday+6)%7;from=new Date(ref.getTime()-diff*86400000);to=new Date(from.getTime()+7*86400000);}else{const [y,m]=day.split('-').map(Number);from=new Date(Date.UTC(y,m-1,1,6));to=new Date(Date.UTC(y,m,1,6));}
 const fmt=d=>new Intl.DateTimeFormat('es-MX',{timeZone:'America/Merida',dateStyle:'medium'}).format(d);
 return {from:from.toISOString(),to:to.toISOString(),label:`${type==='week'?'Semana':'Mes'} del ${fmt(from)} al ${fmt(new Date(to.getTime()-1))}`};
}
async function prepareSalesReport(){if(!reportOwner())return;const container=document.getElementById('salesReportContent'),request=++salesReportRequest;document.querySelectorAll('[data-report-export]').forEach(b=>b.disabled=true);salesReportData=null;container.innerHTML='<p>Preparando reporte completo…</p>';try{const bounds=calendarReportBounds(document.getElementById('reportPeriod').value,document.getElementById('reportDay').value),d=await getSalesSummary(bounds);if(request!==salesReportRequest)return;salesReportData={...d,label:bounds.label,demo:!!window.PasteHotDemo};container.innerHTML=salesReportBody(salesReportData);document.querySelectorAll('[data-report-export]').forEach(b=>b.disabled=false);}catch{if(request===salesReportRequest)container.innerHTML='<div class="message error">No se pudo generar el reporte. Revisa la conexión y vuelve a intentar. No se exportan resultados incompletos.</div>';}}
let salesReportRequest=0;
function salesReportBody(d){const units=d.pastes.reduce((n,p)=>n+Number(p.quantity),0),best=d.pastes.filter(p=>p.quantity>0),least=d.pastes.length?Math.min(...d.pastes.map(p=>p.quantity)):null;return `<h1>PasteHot · Reporte de ventas</h1><p>${escapeHtml(d.label)}</p><p>Generado: ${escapeHtml(storeEventTime(d.generated_at))} · Hora de Mérida${d.demo?' · DATOS DE PRUEBA':''}</p><p><strong>Pedidos registrados: ${d.orders} · Ventas totales: ${formatMoney(d.total)} · Pastes vendidos: ${units}</strong></p><p>Más vendido: ${escapeHtml(best[0]?.name||'Sin ventas')}. Menor venta: ${escapeHtml(d.pastes.filter(p=>p.quantity===least).map(p=>p.name).join(', ')||'Sin productos')}.</p><table><thead><tr><th>Posición</th><th>Paste</th><th>Unidades</th><th>Venta del paste</th></tr></thead><tbody>${d.pastes.map((p,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(p.name)}</td><td>${p.quantity}</td><td>${formatMoney(p.amount)}</td></tr>`).join('')||'<tr><td colspan="4">Sin productos.</td></tr>'}</tbody></table><h2>Ventas por día</h2><table><thead><tr><th>Fecha</th><th>Venta total</th></tr></thead><tbody>${d.daily.map(r=>`<tr><td>${escapeHtml(r.day)}</td><td>${formatMoney(r.amount)}</td></tr>`).join('')||'<tr><td colspan="2">Sin ventas.</td></tr>'}</tbody></table><p class="report-note">Excluye pedidos cancelados y pendientes de confirmar. Las ventas reflejan pedidos registrados; no certifican que el pago haya sido recibido. El total incluye bebidas y entrega; la venta de cada paste usa su precio registrado al comprar. No se calculan utilidades. La semana va de lunes a domingo y el mes es calendario. Los periodos en curso muestran lo registrado hasta la fecha de generación.</p>`;}
const reportStyle='body{font-family:Arial,sans-serif;font-size:11pt;color:#111;margin:24px}h1{font-size:20pt}h2{font-size:14pt;margin-top:24px}p{line-height:1.4}table{width:100%;border-collapse:collapse;margin:14px 0}th,td{padding:8px;border:1px solid #bbb;text-align:left}th{background:#eee}thead{display:table-header-group}tr{break-inside:avoid}.report-note{font-size:9pt;color:#555}@page{size:A4;margin:18mm}@media print{.print-controls{display:none}body{margin:0}h1,h2{break-after:avoid}}';
function printSalesReport(){if(!reportOwner()||!salesReportData)return;const popup=window.open('','_blank');if(!popup){alert('Permite abrir ventanas para ver el reporte y guardarlo como PDF.');return;}popup.document.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>PasteHot Reporte de ventas</title><style>${reportStyle}</style></head><body><div class="print-controls"><button onclick="window.print()">Imprimir o guardar PDF</button><p>En el destino de impresión puedes elegir Guardar como PDF.</p></div>${salesReportBody(salesReportData)}</body></html>`);popup.document.close();popup.focus();}
function downloadReportFile(bytes,type,name){const blob=new Blob([bytes],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function reportFileName(ext){return `PasteHot-ventas-${document.getElementById('reportPeriod').value}-${document.getElementById('reportDay').value}.${ext}`;}
function exportSalesCsv(){if(!reportOwner()||!salesReportData)return;downloadReportFile('\ufeff'+csvText([['PasteHot',salesReportData.label],['Paste','Unidades','Venta del paste'],...salesReportData.pastes.map(p=>[p.name,p.quantity,p.amount]),['Pedidos',salesReportData.orders],['Ventas totales',salesReportData.total]]),'text/csv;charset=utf-8',reportFileName('csv'));}
function csvText(rows){return rows.map(row=>row.map(value=>{let s=String(value??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(',')).join('\r\n');}
function downloadSalesWord(){if(!reportOwner()||!salesReportData)return;downloadReportFile(salesDocx(salesReportData),'application/vnd.openxmlformats-officedocument.wordprocessingml.document',reportFileName('docx'));}
function salesDocx(d){
 const xml=s=>String(s??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
 const paragraph=(t,style='')=>`<w:p><w:pPr>${style?`<w:pStyle w:val="${style}"/>`:''}</w:pPr><w:r><w:t xml:space="preserve">${xml(t)}</w:t></w:r></w:p>`;
 const table=(rows)=>`<w:tbl><w:tblPr><w:tblW w:w="9638" w:type="dxa"/><w:tblBorders>${['top','left','bottom','right','insideH','insideV'].map(b=>`<w:${b} w:val="single" w:sz="4" w:color="BBBBBB"/>`).join('')}</w:tblBorders></w:tblPr>${rows.map((row,i)=>`<w:tr><w:trPr><w:cantSplit/>${i===0?'<w:tblHeader/>':''}</w:trPr>${row.map(v=>`<w:tc><w:tcPr><w:tcW w:w="${Math.floor(9638/row.length)}" w:type="dxa"/>${i===0?'<w:shd w:fill="EEEEEE"/>':''}</w:tcPr>${paragraph(v)}</w:tc>`).join('')}</w:tr>`).join('')}</w:tbl>`;
 const content=paragraph('PasteHot Reporte de ventas','Title')+paragraph(d.label)+paragraph(`Generado ${storeEventTime(d.generated_at)} · Hora de Mérida${d.demo?' · DATOS DE PRUEBA':''}`)+paragraph(`Pedidos ${d.orders} · Ventas totales ${formatMoney(d.total)} · Pastes vendidos ${d.pastes.reduce((n,p)=>n+Number(p.quantity),0)}`)+paragraph(`Más vendido ${d.pastes.filter(p=>p.quantity>0)[0]?.name||'Sin ventas'}. Menor venta ${d.pastes.filter(p=>p.quantity===Math.min(...d.pastes.map(r=>r.quantity))).map(p=>p.name).join(', ')||'Sin productos'}.`)+paragraph('Venta por paste','Heading1')+table([['Posición','Paste','Unidades','Venta del paste'],...d.pastes.map((p,i)=>[i+1,p.name,p.quantity,formatMoney(p.amount)])])+paragraph('Ventas por día','Heading1')+table([['Fecha','Venta total'],...d.daily.map(r=>[r.day,formatMoney(r.amount)])])+paragraph('Excluye cancelados y pendientes de confirmar. Ventas de pedidos registrados, no comprobación de pagos. El total incluye bebidas y entrega. Los importes por paste usan su precio al comprar. No representa utilidades. Semana de lunes a domingo y mes calendario. Los periodos en curso incluyen lo registrado hasta generar el reporte.');
 const files={'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>',
 '_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
 'word/_rels/document.xml.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 'word/styles.xml':'<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:sz w:val="22"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="120"/></w:pPr></w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:pPr><w:keepNext/><w:spacing w:after="240"/></w:pPr><w:rPr><w:b/><w:sz w:val="36"/><w:color w:val="000000"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:pPr><w:keepNext/><w:spacing w:before="240" w:after="160"/></w:pPr><w:rPr><w:b/><w:sz w:val="28"/></w:rPr></w:style></w:styles>',
 'word/document.xml':`<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${content}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`};return reportZip(files);
}
function reportZip(files){const enc=new TextEncoder(),parts=[],central=[];let offset=0;const header=n=>new DataView(new ArrayBuffer(n)),crc=b=>{let c=0xffffffff;for(const v of b){c^=v;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;};
 for(const [name,content] of Object.entries(files)){const n=enc.encode(name),b=typeof content==='string'?enc.encode(content):content,c=crc(b),h=header(30);h.setUint32(0,0x04034b50,true);h.setUint16(4,20,true);h.setUint16(6,0x800,true);h.setUint32(14,c,true);h.setUint32(18,b.length,true);h.setUint32(22,b.length,true);h.setUint16(26,n.length,true);parts.push(new Uint8Array(h.buffer),n,b);const ch=header(46);ch.setUint32(0,0x02014b50,true);ch.setUint16(4,20,true);ch.setUint16(6,20,true);ch.setUint16(8,0x800,true);ch.setUint32(16,c,true);ch.setUint32(20,b.length,true);ch.setUint32(24,b.length,true);ch.setUint16(28,n.length,true);ch.setUint32(42,offset,true);central.push(new Uint8Array(ch.buffer),n);offset+=30+n.length+b.length;}
 const len=central.reduce((n,b)=>n+b.length,0),end=header(22);end.setUint32(0,0x06054b50,true);end.setUint16(8,Object.keys(files).length,true);end.setUint16(10,Object.keys(files).length,true);end.setUint32(12,len,true);end.setUint32(16,offset,true);const chunks=[...parts,...central,new Uint8Array(end.buffer)],out=new Uint8Array(chunks.reduce((n,b)=>n+b.length,0));let i=0;chunks.forEach(b=>{out.set(b,i);i+=b.length;});return out;
}
async function exportOrdersBackup(){if(!reportOwner())return;const button=document.getElementById('ordersBackup');button.disabled=true;try{const rows=[['Folio','Fecha Mérida','Estado','Total MXN','Pago','Tipo de entrega','Productos']],to=new Date().toISOString();let cursor=null;
 for(;;){if(!reportOwner())throw new Error('SESION_CAMBIO');let q=db.from('orders').select('id,order_code,created_at,order_status,total,payment_method,delivery_type,items').lt('created_at',to).order('created_at',{ascending:false}).order('id',{ascending:false});if(cursor)q=q.or(`created_at.lt.${cursor.created_at},and(created_at.eq.${cursor.created_at},id.lt.${cursor.id})`);const {data,error}=await q.limit(500);if(error)throw error;data.forEach(o=>rows.push([o.order_code||o.id,storeEventTime(o.created_at),o.order_status,o.total,o.payment_method,o.delivery_type,safeItems(o.items).map(i=>`${i.name} × ${i.quantity}`).join('; ')]));if(data.length<500)break;cursor=data.at(-1);}
 if(!reportOwner())throw new Error('SESION_CAMBIO');downloadReportFile('\ufeff'+csvText(rows),'text/csv;charset=utf-8',`PasteHot-pedidos-${localReportDay()}.csv`);}catch{alert('No se pudo completar la exportación. No se descargó un archivo parcial.');}finally{button.disabled=false;}}
async function exportStoreBackup(){if(!reportOwner())return;const rows=[['Fecha Mérida','Movimiento','Responsable','Rol','Dispositivo','Motivo','En horario laboral']],seen=new Set();let firstId=null;try{for(let offset=0;;offset+=50){if(!reportOwner())throw new Error('SESION_CAMBIO');const {data,error}=await db.rpc('pastehot_store_history',{p_day:null,p_offset:offset,p_only_during_hours:false});if(error)throw error;if(firstId===null&&data.rows.length)firstId=BigInt(data.rows[0].id);data.rows.forEach(e=>{const id=String(e.id);if(seen.has(id)||(firstId!==null&&BigInt(id)>firstId))return;seen.add(id);rows.push([storeEventTime(e.created_at),e.closed?'Cierre':'Restablecimiento',e.actor_name,e.actor_role,e.session_label,e.reason,e.during_hours?'Sí':'No']);});if(!data.has_more)break;}if(reportOwner())downloadReportFile('\ufeff'+csvText(rows),'text/csv;charset=utf-8',`PasteHot-historial-tienda-${localReportDay()}.csv`);}catch{alert('No se pudo completar el historial. No se descargó un archivo parcial.');}}
function installAdminReports(){window.pastehotLegacyOrderTable=renderOrdersTable;loadOrders=loadOrdersOptimized;renderOrdersTable=()=>{orderPageRows=orderPageRows.map(o=>orders.find(r=>r.id===o.id)||o);renderOrderPage();};renderOrderAnalytics=renderServerAnalytics;renderPasteSales=renderServerPasteSales;renderCustomers=renderServerCustomers;document.getElementById('reportDay').value=localReportDay();}
