const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.join(__dirname,'..'),sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const html=fs.readFileSync(root+'/admin.html','utf8'),dom=new JSDOM(html,{url:'https://deploy-preview-6--cheerful-daifuku-76579b.netlify.app/admin.html?demo=1',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.alert=()=>{};w.confirm=()=>true;
 const files=['receipt.js','admin-orders.js','admin-preview-demo.js','admin-access.js','admin-store-control.js','admin-reports.js','admin-image-maintenance.js','admin-live-sync.js'];
 const inline=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].find(m=>!m[1].includes('src=')&&m[2].includes('SUPABASE_URL'))[2];w.eval(files.map(f=>fs.readFileSync(root+'/'+f,'utf8')).join('\n')+'\n'+inline);await sleep(100);w.showTab('access');await sleep(50);
 for(const id of ['loginPassword','staffAccountPassword','staffNewPassword','staffRepeatPassword']){const input=w.document.getElementById(id),button=w.document.querySelector('[aria-controls="'+id+'"]');assert.equal(input.type,'password');w.togglePassword(id,button);assert.equal(input.type,'text');assert.equal(button.getAttribute('aria-pressed'),'true');w.togglePassword(id,button);assert.equal(input.type,'password');assert.equal(button.getAttribute('aria-label'),'Mostrar contraseña');}
 const username=w.document.getElementById('staffAccountUsername'),name=w.document.getElementById('staffInviteName'),password=w.document.getElementById('staffAccountPassword'),role=w.document.getElementById('staffInviteRole'),message=w.document.getElementById('staffAccountMessage'),toast=w.document.getElementById('accountCreatedToast'),event={preventDefault(){}};
 name.value='Encargado';username.value='encargado.nuevo';password.value='corta';role.value='manager';await w.createAdminStaff(event);assert(message.textContent.includes('12 a 128'));assert.equal(password.value,'corta');assert(toast.classList.contains('hidden'));
 const client=w.PasteHotDemo.client,invoke=client.functions.invoke;password.value='ClaveDePrueba123!';let calls=0,release;
 client.functions.invoke=async()=>{calls++;return {data:null,error:{context:{json:async()=>({error:'Usuario ya existe'})}}};};await w.createAdminStaff(event);assert.equal(calls,1);assert.equal(password.value,'ClaveDePrueba123!');assert.equal(username.value,'encargado.nuevo');assert(message.textContent.includes('Usuario ya existe'));assert(toast.classList.contains('hidden'));
 client.functions.invoke=async()=>{throw new Error('offline');};await w.createAdminStaff(event);assert(message.textContent.includes('No se pudo conectar'));assert.equal(password.value,'ClaveDePrueba123!');assert(toast.classList.contains('hidden'));
 client.functions.invoke=async()=>({data:{},error:null});await w.createAdminStaff(event);assert(toast.classList.contains('hidden'));assert.equal(password.value,'ClaveDePrueba123!');
 client.functions.invoke=async(...args)=>{calls++;assert.equal(args[0],'pastehot-create-staff-preview');await new Promise(r=>release=r);return invoke(...args);};const request=w.createAdminStaff(event);await sleep(10);assert(role.disabled);await w.createAdminStaff(event);assert.equal(calls,2);release();await request;
 assert(!toast.classList.contains('hidden'));assert(toast.textContent.includes('Cuenta activada con éxito'));assert(toast.textContent.includes('encargado.nuevo'));assert.equal(password.value,'');assert.equal(w.PasteHotDemo.state.members.at(-1).role,'manager');const list=w.document.getElementById('accessMembers');assert(list.textContent.includes('Usuario: encargado.nuevo'));assert(list.textContent.includes('Contraseña actual: protegida'))&&assert(list.textContent.includes('Cambiar y copiar contraseña'));assert(!list.textContent.includes('ClaveDePrueba123!'));assert.equal(w.document.getElementById('createdAccountPassword').textContent,'ClaveDePrueba123!');
 const resetMember=w.PasteHotDemo.state.members.at(-1);w.openResetAccountPassword(resetMember.user_id);assert(w.document.getElementById('accountPasswordModal').classList.contains('show'));w.document.getElementById('accountNewPassword').value='NuevaClaveReset123!';client.functions.invoke=invoke;await w.submitAccountPasswordReset({preventDefault(){}});assert(w.document.getElementById('accountPasswordResetMessage').textContent.includes('Contraseña actualizada'));assert.equal(w.document.getElementById('accountNewPassword').value,'NuevaClaveReset123!');w.closeAccountPasswordModal();
 client.functions.invoke=invoke;name.value='Propietario delegado';username.value='propietario.nuevo';password.value='OtraClaveDePrueba123!';role.value='owner';await w.createAdminStaff(event);assert.equal(w.PasteHotDemo.state.members.at(-1).role,'owner');
 await w.demoRole('delegated');await sleep(60);const principal=w.PasteHotDemo.state.members.find(m=>m.primary_owner),delegated=w.PasteHotDemo.state.members.find(m=>m.role==='owner'&&!m.primary_owner);assert(w.document.getElementById('accessMembers').textContent.includes('Cambiar mi contraseña'));let selfPassword='';client.auth.updateUser=async({password})=>{selfPassword=password;return {error:null}};client.auth.signOut=async({scope})=>({error:scope==='others'?null:new Error('scope')});w.openResetAccountPassword(delegated.user_id);w.document.getElementById('accountNewPassword').value='NuevaClaveOwner123!';await w.submitAccountPasswordReset({preventDefault(){}});assert.equal(selfPassword,'NuevaClaveOwner123!');assert(w.document.getElementById('accountPasswordResetMessage').textContent.includes('otras sesiones cerradas'));w.closeAccountPasswordModal();await w.deleteAdminMember(principal.user_id);await w.changeAdminMember(principal.user_id,false);await w.changeAdminMemberRole(principal.user_id,'staff');assert.equal(principal.role,'owner');assert(principal.enabled);assert(w.PasteHotDemo.state.members.includes(principal));
 await w.demoRole('manager');await sleep(60);assert(!w.document.getElementById('section-access').classList.contains('active'));assert.equal(w.document.getElementById('accessMembers').textContent.includes('encargado.nuevo'),false);assert(w.document.getElementById('staffInviteForm').classList.contains('hidden'));
 w.stopAdminEnhancements();dom.window.close();console.log('PASS: password eyes; visible validation and preserved failed drafts; no false success; double-submit prevention; manager/owner registration, private account list and protected principal.');
})().catch(e=>{console.error(e);process.exit(1);});
